[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "chmod -R 777 storage bootstrap/cache"
]

[start]
cmd = "php artisan config:clear && php artisan migrate --force && php artisan db:seed --force && /start-container.sh"