[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "chmod -R 777 storage bootstrap/cache",
  "cp start.sh /start-container.sh",
  "chmod +x /start-container.sh"
]

[start]
cmd = "php artisan config:clear && php artisan migrate --force && php artisan db:seed --force && /start-container.sh"