[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "php artisan config:clear",
  "php artisan config:cache",
  "php artisan route:cache",
  "chmod -R 777 storage bootstrap/cache"
]

[start]
cmd = "php artisan migrate --force && /start-container.sh"